---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: update-open5gs
  namespace: pacman-app
  labels:
    app.kubernetes.io/name: pacman
  generateName: open5gs-demo-acm-gitops-job-
spec:
  extra_vars:
    app_namespace: open5gs-demo-acm
    service_account: 5gcore
  job_template_name: "Update open5gs deployment"
  tower_auth_secret: aap2-secrets
